### PR TITLE
Fixed two exceptions caused by Unity Upgrade

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Moved initialization of two Texture2D variables from the class variables being initialized into a new Awake() method.  Full info in issue #83

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Note:  I was unable to compile because of missing resources, but the syntax passed VS checks

**Comment by Sigma88** [comment]
hi @linuxgurugamer,

thank you for taking the time, I looked at this PR and everything seems fine to me.

if you care about me merging this PR into my mod I have a couple of requests:

1. could you please push against the "Development" branch
2. could you remove the extra files included in the obj/ folders

if you don't care about the github statistics I can just apply the changes manually myself, but I thought I mentioned it in case you like having your name in the repository stats

thanks again for pointing this out

**Comment by linuxgurugamer** [comment]
I jus saw that some temporary files got uploaded.
Redoing it now

**Comment by linuxgurugamer** [comment]
I'll pull down the develop branch and redo this

**Comment by Sigma88** [comment]
I think you can just push that agains the development branch
it should be the same as the master branch at this moment, however I need to do more development stuff on the mods so I would rather have the changes there

**Pull request closed without merging**
